### ISSUE TITLE
右上角小图标的颜色可以设置颜色吗？

### ISSUE THREAD

**Issue by hzq-up** [leochan2017/kms-jsmind#12]
右上角小图标的颜色可以设置颜色吗？我需要根据后端传给我的一个字段的大小来设置不同的颜色

**Comment by leochan2017** [comment]
> 右上角小图标的颜色可以设置颜色吗？我需要根据后端传给我的一个字段的大小来设置不同的颜色

此库没有维护了，你可以clone 下来 改一下符合实际业务使用
